# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-18 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventoryId', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=50)),
                ('amount', models.IntegerField(null=True)),
                ('max_amount', models.IntegerField(null=True)),
                ('min_amount', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemId', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=50)),
                ('itemModel', models.CharField(max_length=50)),
                ('remark', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StockBill',
            fields=[
                ('stockBillId', models.AutoField(primary_key=True, serialize=False)),
                ('stockBillCode', models.CharField(max_length=40)),
                ('stockDate', models.DateTimeField(null=True)),
                ('operator', models.CharField(max_length=40)),
                ('amount', models.IntegerField(null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item'),
        ),
    ]
