# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-24 05:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_code', models.CharField(max_length=40)),
                ('bill_date', models.DateTimeField(null=True)),
                ('bill_operator', models.CharField(max_length=40)),
                ('bill_amount', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='stockbill',
            name='item',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='amount',
            new_name='inventory_amount',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='inventoryId',
            new_name='inventory_id',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='item',
            new_name='inventory_item',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='max_amount',
            new_name='inventory_max_amount',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='min_amount',
            new_name='inventory_min_amount',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='position',
            new_name='inventory_position',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='itemId',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='itemModel',
            new_name='item_model',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='itemName',
            new_name='item_name',
        ),
        migrations.DeleteModel(
            name='StockBill',
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item'),
        ),
    ]
